Replace deprecated `...` range syntax with `..=`
Follow up https://github.com/rust-lang/book/pull/1977.

`...` を使った範囲は、現在の Rust 処理系 (1.60.0) だと以下のエラーになります。

```
error[E0783]: `...` range patterns are deprecated
```

この PR は `...` 構文を、新たな `..=` 構文に置換します。
また `..=` 周辺のコーディングフォーマットについて、`..=` の前後に空白がない
原文にあわせて空白をトリムしています。